import React, {ReactNode} from "react";
import type {Metadata} from 'next'

import ModulePage from "@/Components/ModulePage";

export const metadata: Metadata = {
    title: 'Create Next sssApp',
    description: 'Generated by create next app',
}

export default function Dash() {
    return <>
        DashBoard
    </>
}